### ISSUE TITLE
反馈StyleableToast库建议

### ISSUE THREAD

**Issue by tcqq** [Muddz/StyleableToast#29]
Change `Builder` to `create` or `builder`best standardized
![image](https://user-images.githubusercontent.com/10644057/36646090-df7092ac-1aad-11e8-847c-6d1cd9d9762a.png)

**Comment by Muddz** [comment]
Hi! Could you please write in english?

**Comment by tcqq** [comment]
I changed, please check.

**Comment by Muddz** [comment]
@tcqq Thanks for the suggestion. I can see it makes more sense with `new StyleableToast.create(this).` instead of `Builder`.  `Builder()` is still here from the times where the builder pattern had `build()` method which is now replaced with `show()`

I will take it into the consideration when making a new update this week

**Comment by tcqq** [comment]
Ok.

**Comment by tcqq** [comment]
Now i think this is the perfect way, because `Builder` or `create` can be omitted.
![image](https://user-images.githubusercontent.com/10644057/36646765-214f17c6-1ab7-11e8-87c9-46c2e85cfe2a.png)

[Google's code is also like this](https://github.com/googlesamples/android-DownloadableFonts/blob/master/app/src/main/java/com/example/android/downloadablefonts/QueryBuilder.java)
