### ISSUE TITLE
Android resource linking failed for 2.1.3+

### ISSUE THREAD

**Issue by nlangh** [Muddz/StyleableToast#47]
When I add your library to my build.gradle I get a Java compiler error during build for release 2.1.3 and upwards. 

> Android resource linking failed
..\android-app\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
..\android-app\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
..\android-app\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2922: error: resource android:attr/fontVariationSettings not found.
..\android-app\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2922: error: resource android:attr/ttcIndex not found.
error: failed linking references.

I use Android Studio 3.3, Gradle 3.3 and compile with the following configuration:
compileSdkVersion 26
minSdkVersion 23
targetSdkVersion 26

**Comment by Oaseru17** [comment]
Same error resource cannot be found

**Comment by Muddz** [comment]
@POORWOLF  @precious171 This is probably related to version `2.1.3` being on `AndroidX`. Try `2.1.2` which is under `android.support` package

**Comment by Muddz** [comment]
@POORWOLF @precious171  Hello again. Sorry I confused the StyleableToast versioning numbers.

Since version `2.1.3` there has been updated version -> `2.2.0` and `2.2.1`
Version `2.2.1` is the on that has been migrated to `AndroidX`. 

Also from version `2.2.0` StyleableToast began to use pre-fixes on the style names to avoid collision with internal Android frameworks and other libraries. 

Please try either of the two version `2.2.0` or `2.2.1` and report back to me how it goes

**Comment by nlangh** [comment]
I had first tried the latest version and saw that it was migrated to AndroidX. So I tested the older versions in descending order. 

The versions 2.2.0 and 2.1.3 led to the same error. The last version I tested is version 2.1.2, which works fine.

**Comment by Muddz** [comment]
@POORWOLF Great!
